 <!-- header.inc --> 
<!DOCTYPE html> 
<html lang="en">
<head>
    	<title>Artworks</title>
    	<meta charset=UTF-8>
		<meta name=viewport content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<script src="zoo.js"></script>
		<link rel=stylesheet href="style.css">
</head>
<body>
<header class="jumbotron">
			<div class="text-center">
				<h1>Welcome to Artworks</h1>
			</div>
		</header>

<!-- end of header.inc -->	                     
